name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  simple_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Simple Script
        run: |
          # Contoh perintah sederhana yang dijalankan dalam skrip
          echo "Hello, World!"
          # Simulasikan kesalahan dengan mengeluarkan status exit 1
          exit 1

  retry_job:
    runs-on: ubuntu-latest
    needs: simple_job
    if: failure()

    steps:
      - name: Retry Job
        uses: actions/steps/retry@v2
        with:
          attempts: 3 # Mengulangi pekerjaan hingga 3 kali jika terjadi kesalahan
          
